language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
  - "pypy3"
services:
  - redis-server
install: 
  - "./scripts/run_tests prepare"
script: 
  - "py.test tests/unit/ --cov pyzor --cov-report term-missing"
  - "py.test tests/functional/"
after_success:
  - coveralls
